- hosts: all
  become: true
  tasks:
  
    - name: Install apache Debian
      apt: 
        name: apache2
        state: present
      when: ansible_os_family == 'Debian'
      
    - name: Install apache CentOS
      yum: 
        name: httpd
        state: present
      when: ansible_os_family == 'RedHat'
