- hosts: all
  become: true
  tasks:
    - name: install python
      raw: "{{ansible_pkg_mgr}} install -y python3"
    - name: Install apache
      apt: 
        name: apache2
        state: present
      when: ansible_os_family == 'Debian'

    - name: copie de la page principale
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
      when: ansible_os_family == 'Debian'
      
    - name: Install apache
      yum: 
        name: httpd
        state: present
      when: ansible_os_family == 'RedHat'
