- hosts: all
  become: true
  tasks:
    - name: Install apache
      apt: 
        name: apache2
        state: present
      when: ansible_os_familly == 'Debian'

    - name: Install apache
      apt: 
        name: httpd
        state: present
      when: ansible_os_familly == 'RedHat'
